name: Test 

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
      - release/*

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./.github/workflows/test_on.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      test-matrix-input: 'Hello,World,This,Is,A,Test'